//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozgunova_Tikkonen_422
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int StatisticsID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> TotalProducts { get; set; }
        public Nullable<decimal> AveragePrice { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
